# Generated by Django 5.0.1 on 2024-03-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefonska_stevilka', models.CharField(max_length=15)),
                ('sporocilo', models.TextField()),
            ],
        ),
    ]
